# 공공데이터 포털 API 설정
data-go-kr:
  api:
    url: http://apis.data.go.kr/1613000/DmstcFlightNvgInfo
    service-key: ${DATA_GO_KR_API_KEY}

server:
  port: 8080

spring:
  application:
    name: spring-ai-fly-schedule-custom


  ai:
    ollama:
      base-url: http://ollama.java21.net
      chat:
        options:
          model: qwen2.5:latest
          temperature: 0.0
          timeout: 300s
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-1.5-flash
            temperature: 0.0
            max-output-tokens: 256
            top-p: 0.9
            top-k: 40

logging:
  level:
    com.nhnacademy.springaiflyschedulecustom: DEBUG
    org.springframework.ai: DEBUG