### @env dev
@serviceKey = oqWzAGWsxHR/cre4r5C2TJD0qw9ldrsGzxIAnDQRIvb31Gt6m/EDMUhczdZ5gIFINhj/QBbAVRTnFuTnBMOJyw==
@baseUrl = https://apis.data.go.kr/1613000/DmstcFlightNvgInfo


### 공항 목록 조회 (JSON)
GET {{baseUrl}}/GetArprtList?serviceKey={{serviceKey}}
Accept: application/